POST http://localhost:3000/api/1.0/appointments
content-type: application/json

{
    "name": "Trixie",
    "age": 18,
    "gender": "f",
    "email": "trixie5@hell.com",
    "date": "2022/04/22",
    "hour": "17:00"
}



###
GET http://localhost:3000/api/1.0/appointments


// busqueda por fechas
###
GET http://localhost:3000/api/1.0/appointments/search?date=2022-04-22


###
GET http://localhost:3000/api/1.0/appointments/d48912d9-10



###
PUT  http://localhost:3000/api/1.0/appointments/bc4bbda6-c
content-type: application/json

{
    "name": "Trixie Decker",
    "age": 18,
    "gender": "O",
    "email": "trixie7@hell.com",
    "date": "2022/04/22",
    "hour": "14:00"
}





###
DELETE  http://localhost:3000/api/1.0/appointments/ec82be9c-7


